icons_format = "{icon}"

[theme]
theme = "ctp-mocha"

[icons]
icons = "awesome4"


[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|} ↓$speed_down ↑$speed_up "

[[block]]
block = "net"
format = "$ip"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 50.0
alert = 20.0
format = " $icon root: $available.eng(w:2) "


[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
device = "BAT0"
format = " $icon $percentage "
full_format = " $icon $percentage "
empty_format = " $icon $percentage "
missing_format = "" 

